version: 2

jobs:
  lint:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run: npm install -g eslint
    - run:
        name: Install Dependencies
        command: yarn install
    - run:
        name: Run Lint
        command: npm run lint

  test:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y curl
      - run: curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - run: apt-get install nodejs -y
      - run: npm install -g mocha
      - run:
          name: Install Dependencies
          command: npm install
      - run: curl https://www.mongodb.org/static/pgp/server-4.0.asc | apt-key add -
      - run: echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main" >> /etc/apt/sources.list.d/mongodb-org-4.0.list
      - run: apt-get update
      - run: apt-get install -y mongodb-org
      - run: service mongodb start
      - run:
          name: Run tests
          command: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy to dirdapi.chaz.pro
          command: |
            ssh $SSH_USER@$SSH_HOST "~/deploy/dirdapi.sh"


workflows:
  version: 2
  build_and_test:
    jobs:
    - lint
    - test
    - deploy:
        requires:
          - test
        filters:
          branches:
            only: master

