version: 2

jobs:
  lint:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run: npm install -g eslint
    - run:
        name: Install Dependencies
        command: yarn install
    - run:
        name: Run Lint
        command: npm run lint

  test:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install nodejs
      - run: npm install -g mocha
      - run:
          name: Install Dependencies
          command: npm install
      - run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
      - run: echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list
      - run: apt-get update
      - run: apt-get install -y mongodb-org
      - run: apt-get clean
      - run: rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      - run:
          name: Run tests
          command: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy to dirdapi.chaz.pro
          command: |
            ssh $SSH_USER@$SSH_HOST "~/deploy/dirdapi.sh"


workflows:
  version: 2
  build_and_test:
    jobs:
    - lint
    - test
    - deploy:
        requires:
          - test
        filters:
          branches:
            only: master

